### ISSUE TITLE
Notes from master review

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/listicle_heading#1]
This looks great! I haven't installed it yet, but comments from a static review:

- [x] Why is there an `&nbsp;` in the readme example?
- [x] Remove the module file since it's empty
- [x] Remove the version from the info.yml file since drupal.org will add that
- [x] Add a screenshot or gif of the module?
- [x] Show the editor experience too?
- [x] Publish to drupal.org?
- [x] Is there an OOP version of `drupal_get_path()`? Perhaps via the ModuleHandler service?
- [x] Should the heading level be configurable? I can't think of a reason where you'd want h1 or h3, but I'm curious.
- [x] Wire up [drupal_tests](https://github.com/deviantintegral/drupal_tests) and add tests?

Feel free to answer questions, file issues, or pull requests as you see fit.

**Comment by juanolalla** [comment]
> Why is there an `&nbsp;` in the readme example?

Because that is how it is currently being rendered in D7, resulting in two empty spaces. I guess we can get rid of that and leave just one, but we should ask them?

**Comment by juanolalla** [comment]
> Publish to drupal.org?

That was one of my questions, I don't know if this module would make sense out of Bravo project or if it's too custom, specially with that two empty spaces.

**Comment by juanolalla** [comment]
> Should the heading level be configurable? I can't think of a reason where you'd want h1 or h3, but I'm curious.

This is another custom hardcoding, they use h2 so I did that. Make the heading level configurable would add more value to the module for other projects, but implementing it adds complexity and takes more time that we don't actually need for the scope of our current project.

**Comment by mattwith** [comment]
Hi @juanolalla, FWIW, I don't see a need for this extra space in the markup. What would be nice is to wrap the `data-number` in a `<span>`. That way that portion of the element could be styled as needed.
```
<h2 class="listing"><span>1.</span> My Sample Heading</h2>
```

**Comment by juanolalla** [comment]
Thanks @mattwith! That is exactly what I needed to know, and the span was also on my mind and I wanted to check it with you, so I'm glad you reviewed this! I had started with a straightforward implementation of what we had in D7 with the shortocode module, and now I will introduce these improvements.

**Comment by deviantintegral** [comment]
Looking at this a day later, the one editorial UX gap I see is in reordering lists. Since the list number is in the source tag, if you move headings around does the editor have to remember to manually update the numbers? I don't think it's a blocker, but might be a nice feature to add to our backlog.

I feel like if the class was configurable, it would be enough to make this worth publishing. As in, I'd _totally_ use this module on lullabot.com.

**Comment by juanolalla** [comment]
Ok, I'm looking at the other shortcodes in deep right now, but I will talk with you before I go back to this module to see what can we do here for a nice user experience.

**Comment by juanolalla** [comment]
I've created a pull request (#2) with all the changes.

For the rest of the questions:

- Now I think it can have value out of this project so I will publish it in drupal.org
- I'm not aware of another way of using drupal_get_path().
- There is no PHP logic in this module, it just implements the class and method to load the CKEditor js plugin. I don't see how Drupal tests could be of any help. It's all JavaScript CKEditor code.

**Comment by deviantintegral** [comment]
Good stuff!

I was thinking of Behat tests for the JS side of things, but https://github.com/Lullabot/listicle_heading/blob/master/src/Plugin/Filter/ListicleHeadingFilter.php looks like it could be tested. It's totally reasonable to leave that aside for now, and perhaps come back to it if you need a change of pace from other work.

**Comment by juanolalla** [comment]
Published in https://www.drupal.org/project/ckeditor_listicle_heading
